# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 439)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setStyleSheet("background-color: #ffffff;\n"
"color: black;\n"
"border: none;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(70, 660, 81, 81))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(70, 570, 81, 81))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(70, 750, 81, 81))
        self.pushButton_28.setObjectName("pushButton_28")
        self.display = QtWidgets.QLineEdit(self.centralwidget)
        self.display.setEnabled(True)
        self.display.setGeometry(QtCore.QRect(0, 0, 411, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.display.setFont(font)
        self.display.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.display.setStyleSheet("background :rgb(230, 230, 230)")
        self.display.setInputMask("")
        self.display.setCursorPosition(1)
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setObjectName("display")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 100, 395, 300))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_clearall = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_clearall.setFont(font)
        self.btn_clearall.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_clearall.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_clearall.setObjectName("btn_clearall")
        self.gridLayout.addWidget(self.btn_clearall, 0, 0, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_clear.setFont(font)
        self.btn_clear.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_clear.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 0, 1, 1, 1)
        self.btn_module = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_module.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_module.setFont(font)
        self.btn_module.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_module.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_module.setObjectName("btn_module")
        self.gridLayout.addWidget(self.btn_module, 0, 2, 1, 1)
        self.btn_off = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_off.setFont(font)
        self.btn_off.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_off.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_off.setObjectName("btn_off")
        self.gridLayout.addWidget(self.btn_off, 0, 3, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_7.setFont(font)
        self.btn_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_7.setStyleSheet("background-color: #424242;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 1, 0, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_8.setFont(font)
        self.btn_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_8.setStyleSheet("background-color: #424242;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 1, 1, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_9.setFont(font)
        self.btn_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_9.setStyleSheet("background-color: #424242;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 1, 2, 1, 1)
        self.btn_divide = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_divide.setFont(font)
        self.btn_divide.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_divide.setStyleSheet("background-color: #ff9800;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_divide.setObjectName("btn_divide")
        self.gridLayout.addWidget(self.btn_divide, 1, 3, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_4.setFont(font)
        self.btn_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_4.setStyleSheet("background-color: #424242;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 2, 0, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_5.setFont(font)
        self.btn_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_5.setStyleSheet("background-color: #424242;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 2, 1, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_6.setFont(font)
        self.btn_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_6.setStyleSheet("background-color: #424242;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 2, 2, 1, 1)
        self.btn_multiply = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_multiply.setFont(font)
        self.btn_multiply.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_multiply.setStyleSheet("background-color: #ff9800;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_multiply.setObjectName("btn_multiply")
        self.gridLayout.addWidget(self.btn_multiply, 2, 3, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_1.setFont(font)
        self.btn_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_1.setStyleSheet("background-color: #424242;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 3, 0, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_2.setFont(font)
        self.btn_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_2.setStyleSheet("background-color: #424242;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 3, 1, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_3.setFont(font)
        self.btn_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_3.setStyleSheet("background-color: #424242;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 3, 2, 1, 1)
        self.btn_add = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_add.setFont(font)
        self.btn_add.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_add.setStyleSheet("background-color: #ff9800;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_add.setObjectName("btn_add")
        self.gridLayout.addWidget(self.btn_add, 3, 3, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_0.setFont(font)
        self.btn_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_0.setStyleSheet("background-color: #424242;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 4, 0, 1, 1)
        self.btn_decimal = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_decimal.setFont(font)
        self.btn_decimal.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_decimal.setStyleSheet("background-color: #424242;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_decimal.setObjectName("btn_decimal")
        self.gridLayout.addWidget(self.btn_decimal, 4, 1, 1, 1)
        self.btn_output = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_output.setFont(font)
        self.btn_output.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_output.setStyleSheet("background-color: #4caf50;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_output.setObjectName("btn_output")
        self.gridLayout.addWidget(self.btn_output, 4, 2, 1, 1)
        self.btn_minus = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.btn_minus.setFont(font)
        self.btn_minus.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_minus.setStyleSheet("background-color: #ff9800;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;")
        self.btn_minus.setObjectName("btn_minus")
        self.gridLayout.addWidget(self.btn_minus, 4, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_25.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_26.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_28.setText(_translate("MainWindow", "PushButton"))
        self.display.setText(_translate("MainWindow", "0"))
        self.btn_clearall.setText(_translate("MainWindow", "AC"))
        self.btn_clearall.setShortcut(_translate("MainWindow", "Ctrl+Space"))
        self.btn_clear.setText(_translate("MainWindow", "C"))
        self.btn_clear.setShortcut(_translate("MainWindow", "Backspace"))
        self.btn_module.setText(_translate("MainWindow", "%"))
        self.btn_off.setText(_translate("MainWindow", "OFF"))
        self.btn_off.setShortcut(_translate("MainWindow", "Ctrl+S, Ctrl+S"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_7.setShortcut(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_8.setShortcut(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_9.setShortcut(_translate("MainWindow", "9"))
        self.btn_divide.setText(_translate("MainWindow", "÷"))
        self.btn_divide.setShortcut(_translate("MainWindow", "/"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_4.setShortcut(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_5.setShortcut(_translate("MainWindow", "5"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_6.setShortcut(_translate("MainWindow", "6"))
        self.btn_multiply.setText(_translate("MainWindow", "×"))
        self.btn_multiply.setShortcut(_translate("MainWindow", "*"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_1.setShortcut(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_2.setShortcut(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_3.setShortcut(_translate("MainWindow", "3"))
        self.btn_add.setText(_translate("MainWindow", "+"))
        self.btn_add.setShortcut(_translate("MainWindow", "+"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_0.setShortcut(_translate("MainWindow", "0"))
        self.btn_decimal.setText(_translate("MainWindow", "."))
        self.btn_decimal.setShortcut(_translate("MainWindow", "."))
        self.btn_output.setText(_translate("MainWindow", "="))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_minus.setShortcut(_translate("MainWindow", "-"))
